version: '2'
networks:
  default:
    name: deploy_default
    external: true
services:
  asralpha-ui:
    build: .
    ports:
      - '3995:3995'
    environment:
      - DOCKER_HOST_IP=$DOCKER_HOST_IP
      - NETSMILE_CONFIGURATION_SERVICE=$NETSMILE_CONFIGURATION_SERVICE
      - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
      - AUTH0_SECRET=$AUTH0_SECRET
      - AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
      - AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL
      - AUTH0_BASE_URL=$AUTH0_BASE_URL
      - USER_SERVICE_API_PROXY_URL=$USER_SERVICE_API_PROXY_URL
      - INTERNAL_API_SECRET=$INTERNAL_API_SECRET
      - USER_SERVICE_API_URL=$USER_SERVICE_API_URL
      - TEMPLATELESS_API_V2_URL=$TEMPLATELESS_API_V2_URL
